### ISSUE TITLE
Create the Python client for Tigris

### ISSUE THREAD

**Issue by ovaistariq** [tigrisdata/tigris-client-python#1]
The API reference can be found at https://www.tigrisdata.com/docs/references/api/ 
Look at the Tigris TypeScript client for an example https://github.com/tigrisdata/tigris-client-ts

**Comment by ibrahim-akrab** [comment]
I would like to tackle this. Should the client use the http api interface or the grpc one?

**Comment by ovaistariq** [comment]
@ibrahim-akrab It should use grpc.

We are using a tool called protoc to generate openapi spec: https://github.com/tigrisdata/tigris-api/blob/main/Makefile#L27

**Comment by ibrahim-akrab** [comment]
@daveads I got busy with something else. You can go ahead and get started.

**Comment by ovaistariq** [comment]
Thanks, @daveads. Please go ahead and take this. Let us know if you run into any issues.

**Comment by bo1658a** [comment]
@ovaistariq , need more Python gigs.

**Comment by daveads** [comment]
yep i will @ovaistariq

**Comment by ndimares** [comment]
Hi @ovaistariq. I put together this Python SDK from the Tigris OpenAPI spec:
https://github.com/speakeasy-sdks/tigris-python-sdk

If Tigris is interested, we could move it into a github repo owned by your team. I made this after speaking with Phil earlier this week. Let me know what you think!

**Comment by daveads** [comment]
@ovaistariq Is there a Slack channel for this project?

**Comment by ovaistariq** [comment]
> @ovaistariq Is there a Slack channel for this project?

@daveads we use Discord: https://www.tigrisdata.com/discord/

**Comment by ovaistariq** [comment]
> Hi @ovaistariq. I put together this Python SDK from the Tigris OpenAPI spec:
> 
> https://github.com/speakeasy-sdks/tigris-python-sdk
> 
> 
> 
> If Tigris is interested, we could move it into a github repo owned by your team. I made this after speaking with Phil earlier this week. Let me know what you think!

@ndimares very cool. Let me take a look at it.

**Comment by ndimares** [comment]
@ovaistariq looking forward to hearing what you think!

**Comment by ovaistariq** [comment]
@ndimares, thank you for spending time generating the Python SDK. We have decided to build the client SDK using the grpc generated client.

**Comment by ovaistariq** [comment]
The first version of the client is complete, closing this out and will create more granular issues.

**Comment by ndimares** [comment]
@ovaistariq all good! Apprciate the response, new SDK looks good anyway 👍

**Comment by ovaistariq** [comment]
> @ovaistariq all good! Apprciate the response, new SDK looks good anyway 👍

Thanks @ndimares
